name: Amazium
favicon: null
layout_spectrum: 0.30908654630184174
typography_spectrum: 0.018409108743071556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.34776151622645557
  lightness: 0.40073109418153763
  saturation: 0.5689753836486489
  rhythmicContrast: 0.8955408791080117
purpose: []
